from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('jinsung3/', views.jinsung3, name='jinsung3'),
    path('동아장왼쪽/', views.dongajangL, name='동아장왼쪽'),
    path('동아장왼쪽/<str:mdname>', views.dongajangLclick),
    path('editdajL/', views.editdajL),
    path('동아장오른쪽/', views.dongajangR, name='동아장오른쪽'),
    path('동아장오른쪽/<str:mdname>', views.dongajangRclick),
    path('editdajR/', views.editdajR),
    path('진성지하/', views.jinsungB, name='진성지하'),
    path('진성지하/<str:mdname>', views.jinsungBclick),
    path('editjinsungB/', views.editjinsungB),
    path('이지넷지하/', views.eznetB, name='이지넷지하'),
    path('이지넷지하/<str:mdname>', views.eznetBclick),
    path('editeznetB/', views.editeznetB),
    path('이지넷1층/', views.eznet1, name='이지넷1층'),
    path('이지넷1층/<str:mdname>', views.eznet1click),
    path('editeznet1/', views.editeznet1),
    path('이지넷2층/', views.eznet2, name='이지넷2층'),
    path('이지넷2층/<str:mdname>', views.eznet2click),
    path('editeznet2/', views.editeznet2),
    path('이지넷3층/', views.eznet3, name='이지넷3층'),
    path('이지넷3층/<str:mdname>', views.eznet3click),
    path('editeznet3/', views.editeznet3),
    path('이지넷4층/', views.eznet4, name='이지넷4층'),
    path('이지넷4층/<str:mdname>', views.eznet4click),
    path('editeznet4/', views.editeznet4),
    path('이지넷5층/', views.eznet5, name='이지넷5층'),
    path('이지넷5층/<str:mdname>', views.eznet5click),
    path('editeznet5/', views.editeznet5),
]
